name: ramadan_nasheed_app
description: Beautiful Offline Ramadan Nasheed App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.39
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1  # Optional for custom icon

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/data/nasheeds.json
    - assets/images/  # If you add background image